from enum import StrEnum


class MessageType(StrEnum):
    TYPE_PING = "TYPE_PING"
    """Проверка статуса готовности сервиса при первичном подключении и периодически после подключения"""
    TYPE_NEW_POSTING = "TYPE_NEW_POSTING"
    """Новое отправление"""
    TYPE_POSTING_CANCELLED = "TYPE_POSTING_CANCELLED"
    """Отмена отправления"""
    TYPE_STATE_CHANGED = "TYPE_STATE_CHANGED"
    """Изменение статуса отправления"""
    TYPE_CUTOFF_DATE_CHANGED = "TYPE_CUTOFF_DATE_CHANGED"
    """Изменение даты отгрузки отправления"""
    TYPE_DELIVERY_DATE_CHANGED = "TYPE_DELIVERY_DATE_CHANGED"
    """Изменение даты доставки отправления"""
    TYPE_CREATE_OR_UPDATE_ITEM = "TYPE_CREATE_OR_UPDATE_ITEM"
    """Создание и обновление товара или ошибка в процессе"""
    TYPE_CREATE_ITEM = "TYPE_CREATE_ITEM"
    """Создание товара или ошибка при его создании"""
    TYPE_UPDATE_ITEM = "TYPE_UPDATE_ITEM"
    """Обновление товара или ошибка при обновлении"""
    TYPE_PRICE_INDEX_CHANGED = "TYPE_PRICE_INDEX_CHANGED"
    """Изменение ценового индекса товара"""
    TYPE_STOCKS_CHANGED = "TYPE_STOCKS_CHANGED"
    """Изменение остатков на складах продавца"""
    TYPE_NEW_MESSAGE = "TYPE_NEW_MESSAGE"
    """Новое сообщение в чате"""
    TYPE_UPDATE_MESSAGE = "TYPE_UPDATE_MESSAGE"
    """Изменение сообщения в чате"""
    TYPE_MESSAGE_READ = "TYPE_MESSAGE_READ"
    """Ваше сообщение прочитано покупателем или поддержкой"""
    TYPE_CHAT_CLOSED = "TYPE_CHAT_CLOSED"
    """Чат закрыт"""
